version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: retail_pos_db_container
    restart: always
    environment:
      MYSQL_DATABASE: retail_pos_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - retail_pos_net

  app:
    build: .
    container_name: retail_pos_app_container
    restart: always
    ports:
      - "8081:8080"
    environment:
      DB_HOST: db
      DB_NAME: retail_pos_db
      DB_USER: root
      DB_PASS: ""
      BASE_URL: "http://localhost:8081/"
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    networks:
      - retail_pos_net

networks:
  retail_pos_net:
    driver: bridge
